font_size: 12
theme: pywal
tree_1:
  general:
    github: "https://github.com/TechnicalDC"
    gmail: "https://mail.google.com/"
  reddit:
    frontpage: 
      - "https://www.reddit.com/"
      - "front page"
    unixporn: "https://www.reddit.com/r/unixporn/"
tree_2:
  other:
    archwiki: 
      - "https://archlinux.org/"
      - "arch wiki"
    youtube: "https://www.youtube.com/"
    savefrom: "https://en.savefrom.net/"
